// Generated by scripts/generate-ai-check-contract.mjs.
// Do not edit by hand; edit ai-check-contract.json and regenerate instead.

import rawContract from "./ai-check-contract.json";

export const AI_CHECK_DECISIONS = ["ALLOW","AI_COOLDOWN","ASK_MORE","BLOCK"] as const;
export type AIDecision = (typeof AI_CHECK_DECISIONS)[number];

export const AI_CHECK_DECISION_REASON_CATEGORIES = ["repeated_excuse","clear_intention","high_risk_pattern","low_risk","insufficient_reason"] as const;
export type DecisionReasonCategory = (typeof AI_CHECK_DECISION_REASON_CATEGORIES)[number];

export const AI_CHECK_BEHAVIOR_REASON_CATEGORIES = ["stress","boredom","loneliness","escape","habit","intentional","other"] as const;
export type BehaviorReasonCategory = (typeof AI_CHECK_BEHAVIOR_REASON_CATEGORIES)[number];

export const AI_CHECK_STRICTNESS_LEVELS = ["gentle","balanced","strict","monk"] as const;
export type StrictnessLevel = (typeof AI_CHECK_STRICTNESS_LEVELS)[number];

export const AI_CHECK_CASE_STATUSES = ["draft","ready","archived"] as const;
export type AICheckCaseStatus = (typeof AI_CHECK_CASE_STATUSES)[number];

export const AI_CHECK_DATASET_TYPES = ["design","regression","holdout"] as const;
export type AICheckDatasetType = (typeof AI_CHECK_DATASET_TYPES)[number];

export const AI_CHECK_PROVENANCE_TYPES = ["authored","session","review"] as const;
export type AICheckProvenanceType = (typeof AI_CHECK_PROVENANCE_TYPES)[number];

export const AI_CHECK_SEVERITY_LEVELS = ["low","medium","high","critical"] as const;
export type AICheckSeverity = (typeof AI_CHECK_SEVERITY_LEVELS)[number];

export const AI_CHECK_BAD_CASE_ERROR_TYPE_VALUES = ["over_allow","over_block","under_ask","unnecessary_ask","wrong_reason_strength","wrong_strictness_application","wrong_cooldown_duration","unsafe_sensitive_advice","bad_tone","schema_or_format_failure"] as const;
export type BadCaseErrorType = (typeof AI_CHECK_BAD_CASE_ERROR_TYPE_VALUES)[number];

export type AICheckScoreName = "repeatedReason" | "impulse" | "deliberateness";
export type AICheckScores = Record<AICheckScoreName, number>;

export interface AICheckCurrentVersions {
  promptVersion: string;
  outputSchemaVersion: string;
  evaluationSchemaVersion: string;
}

export interface AICheckSchemaFieldReference {
  path: string;
  type: string;
  required: boolean;
  nullable?: boolean;
  example?: unknown;
  meaning: string;
  whyNecessary: string;
  productImpact: string;
  validation: string;
  commonMistakes: string;
}

export interface AICheckContractSection {
  title: string;
  summary: string;
  fields: AICheckSchemaFieldReference[];
  example: unknown;
  schemaSummary?: string;
  promptSchema?: unknown;
}

export interface AICheckPromptProgramRule {
  id: string;
  label: string;
  rule: string;
  rationale: string;
  riskIfIgnored: string;
}

export interface AICheckPromptProgramContract {
  decisionPolicyRules: AICheckPromptProgramRule[];
  scoringRules: AICheckPromptProgramRule[];
}

export type AICheckContractSchemaNode =
  | { type: "string"; required: boolean; nullable?: boolean }
  | { type: "number"; required: boolean; nullable?: boolean; min?: number; max?: number }
  | { type: "boolean"; required: boolean }
  | { type: "enum"; required: boolean; enum?: string; values?: string[] }
  | { type: "array"; required: boolean; item: AICheckContractSchemaNode }
  | { type: "object"; required: boolean; title?: string; summary?: string; fields: Record<string, AICheckContractSchemaNode> }
  | { type: "ref"; required: boolean; ref: "input" | "output" | "evaluation" }
  | { type: "union"; required: boolean; variants: AICheckContractSchemaNode[] }
  | { type: "nullableNumberExpectation"; required: boolean }
  | { type: "nullableTextExpectation"; required: boolean }
  | { type: "numberRangeExpectation"; required: boolean };

interface AICheckVersionRegistryEntry {
  version: string;
  label: string;
  current?: boolean;
  section?: AICheckContractSection;
}

export interface AICheckResolvedVersionEntry {
  version: string;
  label: string;
  current: boolean;
  section: AICheckContractSection;
}

export interface AICheckContract {
  id: string;
  outputSchemaVersion: string;
  promptVersion: string;
  evaluationSchemaVersion: string;
  current: AICheckCurrentVersions;
  versionRegistry: {
    prompts: Array<Omit<AICheckVersionRegistryEntry, "section">>;
    outputSchemas: AICheckVersionRegistryEntry[];
    evaluationSchemas: AICheckVersionRegistryEntry[];
  };
  sessionPolicy: {
    maxAssistantTurns: number;
    maxSessionSeconds: number;
  };
  promptProgram: AICheckPromptProgramContract;
  enums: {
    decisions: AIDecision[];
    decisionReasonCategories: DecisionReasonCategory[];
    behaviorReasonCategories: BehaviorReasonCategory[];
    strictnessLevels: StrictnessLevel[];
    caseStatuses: AICheckCaseStatus[];
    datasetTypes: AICheckDatasetType[];
    provenanceTypes: AICheckProvenanceType[];
    severityLevels: AICheckSeverity[];
    badCaseErrorTypes: BadCaseErrorType[];
  };
  schemas: {
    input: AICheckContractSchemaNode;
    output: AICheckContractSchemaNode;
    evaluation: AICheckContractSchemaNode;
  };
  examples: {
    input: unknown;
    output: unknown;
    evaluation: unknown;
  };
  pmReview: {
    fieldDocs: Record<"input" | "output" | "evaluation", Record<string, Omit<AICheckSchemaFieldReference, "path" | "type" | "required" | "nullable" | "example">>>;
    errorTypes: Array<{ value: BadCaseErrorType; label: string }>;
    commonTags: string[];
    caseSets: Array<{
      id: string;
      name: string;
      description: string;
      statuses: AICheckCaseStatus[];
      datasetTypes?: AICheckDatasetType[];
      tags?: string[];
      includeArchived?: boolean;
    }>;
  };
  sections: {
    input: AICheckContractSection;
    output: AICheckContractSection & {
      schemaSummary: string;
      promptSchema: unknown;
    };
    evaluation: AICheckContractSection;
  };
}

export interface AICheckCaseInput {
  targetDisplay: string;
  strictness: StrictnessLevel;
  sessionContext: {
    assistantTurnCount: number;
    maxAssistantTurns: number;
    isFinalTurn: boolean;
  };
  messages: Array<{
    role: "system" | "assistant" | "user";
    content: string;
    source: "local_opening" | "user" | "llm" | "system";
  }>;
  patternMemorySnapshot: Array<{
    id?: string;
    targetDisplay: string;
    behaviorReasonCategory: BehaviorReasonCategory;
    repeatedCount: number;
    lastUserReason: string;
    guidance: string;
    updatedAt: string;
  }>;
}

export interface CheckpointDecision {
  id: string;
  sessionId: string;
  decision: AIDecision;
  userFacingMessage: string;
  decisionReasonCategory: DecisionReasonCategory;
  unlockMinutes: number | null;
  aiCooldownSeconds: number | null;
  aiCooldownNormalization?: {
    originalSeconds: number;
    normalizedSeconds: number;
    minSeconds: number;
    maxSeconds: number;
  };
  scores: AICheckScores;
  memoryUpdate: {
    behaviorReasonCategory: BehaviorReasonCategory;
    patternNote: string | null;
  };
  createdAt: string;
  rawProvider?: string;
}

export interface AICheckCaseOutput {
  provider?: string;
  model?: string;
  rawProvider?: string;
  parsed: Omit<CheckpointDecision, "id" | "sessionId" | "createdAt" | "decisionReasonCategory" | "memoryUpdate"> & {
    decisionReasonCategory: DecisionReasonCategory;
    memoryUpdate: {
      behaviorReasonCategory: BehaviorReasonCategory;
      patternNote: string | null;
    };
  };
}

export type AICheckDecisionExpectation =
  | AIDecision
  | {
      exact?: AIDecision;
      allowed?: AIDecision[];
      disallowed?: AIDecision[];
    };

export interface AICheckTextExpectation {
  exact?: string;
  mustMention?: string[];
  mustNotMention?: string[];
}

export interface AICheckNullableTextExpectation {
  exact?: string | null;
  mustMention?: string[];
  mustNotMention?: string[];
}

export interface AICheckNullableNumberExpectation {
  exact?: number | null;
  min?: number;
  max?: number;
}

export interface AICheckNumberRangeExpectation {
  min?: number;
  max?: number;
}

export interface AICheckExpectedOutput {
  decision?: AICheckDecisionExpectation;
  userFacingMessage?: AICheckTextExpectation;
  decisionReasonCategory?: DecisionReasonCategory;
  unlockMinutes?: AICheckNullableNumberExpectation;
  aiCooldownSeconds?: AICheckNullableNumberExpectation;
  scores?: Partial<Record<AICheckScoreName, AICheckNumberRangeExpectation>>;
  memoryUpdate?: {
    behaviorReasonCategory?: BehaviorReasonCategory;
    patternNote?: AICheckNullableTextExpectation;
  };
}

export interface AICheckExpectedInputEvidence {
  hasExplicitDuration?: boolean;
  hasReturnPlan?: boolean;
}

export interface AICheckCaseEval {
  expectedOutput: AICheckExpectedOutput;
  expectedInputEvidence?: AICheckExpectedInputEvidence;
  tags: string[];
  reviewerNote?: string;
}

export type AICheckCaseProvenance =
  | { type: "authored"; author?: string }
  | { type: "session"; sessionId?: string; decisionId?: string }
  | { type: "review"; reviewId?: string; sessionId?: string; decisionId?: string };

export interface AICheckCaseLineage {
  parentCaseId?: string;
  supersedesCaseIds?: string[];
  splitFromCaseId?: string;
  mergedFromCaseIds?: string[];
}

export interface AICheckCase {
  id: string;
  title: string;
  datasetType: AICheckDatasetType;
  provenance: AICheckCaseProvenance;
  lineage?: AICheckCaseLineage;
  versions: AICheckCurrentVersions;
  input: AICheckCaseInput;
  output?: AICheckCaseOutput;
  eval?: AICheckCaseEval;
  status: AICheckCaseStatus;
  severity?: AICheckSeverity;
  archivedAt?: string;
  archivedReason?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface AICheckEvalRunFilters {
  statuses?: AICheckCaseStatus[];
  datasetTypes?: AICheckDatasetType[];
  tags?: string[];
  strictness?: StrictnessLevel[];
  expectedDecisions?: AIDecision[];
  severity?: AICheckSeverity[];
  includeArchived?: boolean;
}

export type AICheckEvalRunMode = "tuning" | "release_review";

export interface AICheckEvalMetricBreakdown {
  key: string;
  passed: number;
  total: number;
  passRate: number;
}

export interface AICheckEvalReleaseGate {
  status: "pass" | "warn" | "fail";
  reasons: string[];
}

export interface AICheckEvalMetrics {
  total: number;
  passed: number;
  failed: number;
  passRate: number;
  byTag: AICheckEvalMetricBreakdown[];
  byStrictness: AICheckEvalMetricBreakdown[];
  falseAllowFailures: number;
  falseBlockFailures: number;
  askMoreRecallFailures: number;
  schemaFailures: number;
  unsafeSensitiveFailures: number;
  reasonQualityFailures: number;
  criticalFailures: number;
  releaseGate: AICheckEvalReleaseGate;
}

export interface AICheckEvalRun {
  id: string;
  promptVersion: string;
  outputSchemaVersion: string;
  evaluationSchemaVersion: string;
  mode: AICheckEvalRunMode;
  providerMode: "mock" | "byok";
  provider: "mock" | "openai" | "deepseek" | "kimi";
  model: string;
  filters: AICheckEvalRunFilters;
  caseIds: string[];
  metrics: AICheckEvalMetrics;
  createdAt: string;
}

export interface AICheckEvalResult {
  id: string;
  runId: string;
  evalCaseId: string;
  actualDecision: AIDecision | null;
  pass: boolean;
  failureReasons: string[];
  rawProvider?: string;
  createdAt: string;
}

const GENERATED_SECTIONS = {
  "input": {
    "title": "Model Input",
    "summary": "The local AI Check context assembled by the extension before calling the provider.",
    "fields": [
      {
        "path": "targetDisplay",
        "type": "string",
        "required": true,
        "example": "youtube.com",
        "meaning": "The blocked target the user is trying to open.",
        "whyNecessary": "The model needs to know which site or URL the user is asking to access.",
        "productImpact": "Anchors the decision in the current blocked target.",
        "validation": "Derived from the local blocked target record.",
        "commonMistakes": "Treating the target as a generic category instead of the concrete blocked target."
      },
      {
        "path": "strictness",
        "type": "gentle | balanced | strict | monk",
        "required": true,
        "example": "strict",
        "meaning": "The active strictness level for the AI Check.",
        "whyNecessary": "Strictness changes unlock caps, cooldown ranges, and how much certainty is required.",
        "productImpact": "Changes decision thresholds and cooldown timing.",
        "validation": "Must be one of the configured strictness levels.",
        "commonMistakes": "Evaluating a case without checking which strictness level applies."
      },
      {
        "path": "sessionContext.assistantTurnCount",
        "type": "number",
        "required": true,
        "example": 1,
        "meaning": "How many assistant turns happened before this model response.",
        "whyNecessary": "The model needs to know whether it can still ask follow-up questions.",
        "productImpact": "Controls when ASK_MORE is still allowed.",
        "validation": "Derived from the local session state.",
        "commonMistakes": "Counting user messages instead of assistant turns."
      },
      {
        "path": "sessionContext.maxAssistantTurns",
        "type": "number",
        "required": true,
        "example": 5,
        "meaning": "Maximum assistant turns allowed in this AI Check.",
        "whyNecessary": "The model needs a bounded conversation limit.",
        "productImpact": "Prevents endless back-and-forth before enforcement.",
        "validation": "Derived from the AI Check session policy.",
        "commonMistakes": "Allowing ASK_MORE after the final turn."
      },
      {
        "path": "sessionContext.isFinalTurn",
        "type": "boolean",
        "required": true,
        "example": false,
        "meaning": "Whether this response is the final allowed assistant turn.",
        "whyNecessary": "Final turns must enforce ALLOW, AI_COOLDOWN, or BLOCK instead of ASK_MORE.",
        "productImpact": "Changes the allowed decision set for this turn.",
        "validation": "Derived from assistantTurnCount and maxAssistantTurns.",
        "commonMistakes": "Returning ASK_MORE when this flag is true."
      },
      {
        "path": "messages",
        "type": "object[]",
        "required": true,
        "example": [
          {
            "role": "assistant",
            "content": "You're trying to open youtube.com. What are you here to do, and why now?",
            "source": "local_opening"
          },
          {
            "role": "user",
            "content": "I just want one quick video.",
            "source": "user"
          }
        ],
        "meaning": "The user-visible AI Check conversation so far.",
        "whyNecessary": "The model must evaluate the user's stated reason and prior assistant prompts.",
        "productImpact": "Determines whether the request is specific, bounded, repeated, or vague.",
        "validation": "System messages are excluded before sending to the provider.",
        "commonMistakes": "Judging only the latest message when earlier turns contain missing context."
      },
      {
        "path": "patternMemorySnapshot",
        "type": "object[]",
        "required": true,
        "example": [],
        "meaning": "Relevant local pattern memory for this target.",
        "whyNecessary": "The model needs long-term behavior context separate from same-session repetition.",
        "productImpact": "Can shift vague repeated behavior toward AI_COOLDOWN or BLOCK.",
        "validation": "Loaded locally and limited before the provider request.",
        "commonMistakes": "Treating same-session repetition as long-term memory without evidence."
      }
    ],
    "example": {
      "targetDisplay": "youtube.com",
      "strictness": "strict",
      "sessionContext": {
        "assistantTurnCount": 1,
        "maxAssistantTurns": 5,
        "isFinalTurn": false
      },
      "messages": [
        {
          "role": "assistant",
          "content": "You're trying to open youtube.com. What are you here to do, and why now?",
          "source": "local_opening"
        },
        {
          "role": "user",
          "content": "I just want one quick video.",
          "source": "user"
        }
      ],
      "patternMemorySnapshot": []
    }
  },
  "output": {
    "title": "Model Output",
    "summary": "The JSON object the provider must return for every AI Check decision.",
    "fields": [
      {
        "path": "decision",
        "type": "ALLOW | AI_COOLDOWN | ASK_MORE | BLOCK",
        "required": true,
        "example": "ASK_MORE",
        "meaning": "The enforcement outcome for the current AI Check turn.",
        "whyNecessary": "The extension needs one explicit outcome to derive temporary unlocks, AI cooldowns, follow-up questions, or block holds.",
        "productImpact": "Directly controls whether the target opens, pauses, asks for more detail, or stays blocked.",
        "validation": "Must be one of the four known decision values.",
        "commonMistakes": "Using free-text decisions or returning ASK_MORE on the final turn."
      },
      {
        "path": "userFacingMessage",
        "type": "string",
        "required": true,
        "example": "What specific task do you need YouTube for, and when will you stop?",
        "meaning": "The calm explanation or follow-up question shown to the user after the decision.",
        "whyNecessary": "The user needs to understand the decision or answer the next ASK_MORE question without seeing internal scoring or policy labels.",
        "productImpact": "Sets tone, trust, and clarity in the block page conversation.",
        "validation": "Must be non-empty. For ASK_MORE, it must be the concrete follow-up question that continues the same session.",
        "commonMistakes": "Shaming the user, overexplaining policy, omitting the concrete next action, or putting the ASK_MORE question in a separate field."
      },
      {
        "path": "decisionReasonCategory",
        "type": "repeated_excuse | clear_intention | high_risk_pattern | low_risk | insufficient_reason",
        "required": true,
        "example": "insufficient_reason",
        "meaning": "The reason category for this specific decision.",
        "whyNecessary": "PM Review and evals need a stable reason label separate from long-term behavior memory.",
        "productImpact": "Explains false allows, false blocks, and strictness behavior in review.",
        "validation": "Unknown labels are normalized where possible, otherwise default from decision.",
        "commonMistakes": "Putting behavior-memory categories such as stress or habit in this field."
      },
      {
        "path": "unlockMinutes",
        "type": "number | null",
        "required": true,
        "nullable": true,
        "example": null,
        "meaning": "Temporary access duration when the decision is ALLOW.",
        "whyNecessary": "ALLOW must produce a bounded unlock instead of permanent access.",
        "productImpact": "Creates the temporary unlock window and caps it by strictness.",
        "validation": "Required for ALLOW and must be within the strictness cap.",
        "commonMistakes": "Returning null for ALLOW or a duration above the strictness limit."
      },
      {
        "path": "aiCooldownSeconds",
        "type": "number | null",
        "required": true,
        "nullable": true,
        "example": null,
        "meaning": "Pause duration when the decision is AI_COOLDOWN.",
        "whyNecessary": "AI cooldown is separate from allow and block; it needs its own timer.",
        "productImpact": "Controls the terminal AI cooldown period before this AI Check ends.",
        "validation": "Required for AI_COOLDOWN and normalized to a sane strictness-derived range.",
        "commonMistakes": "Using legacy delay fields or returning cooldown seconds for non-cooldown decisions."
      },
      {
        "path": "scores.repeatedReason",
        "type": "0-100 number",
        "required": true,
        "example": 20,
        "meaning": "How strongly this resembles a repeated or previously remembered reason.",
        "whyNecessary": "The model needs a numeric signal that can be evaluated independently from the decision label.",
        "productImpact": "Helps review repeated-excuse failures and regression strictness.",
        "validation": "Must be a finite number between 0 and 100; rounded to an integer.",
        "commonMistakes": "Treating the three scores as percentages that must sum to 100."
      },
      {
        "path": "scores.impulse",
        "type": "0-100 number",
        "required": true,
        "example": 62,
        "meaning": "How impulsive or reactive the current request appears.",
        "whyNecessary": "Cooldown and block decisions depend on impulse risk, especially in stricter modes.",
        "productImpact": "Supports PM diagnosis of over-allow and under-ask cases.",
        "validation": "Must be a finite number between 0 and 100; rounded to an integer.",
        "commonMistakes": "Leaving it low for vague, emotional, or repeated requests."
      },
      {
        "path": "scores.deliberateness",
        "type": "0-100 number",
        "required": true,
        "example": 35,
        "meaning": "How specific, bounded, and intentional the user's plan appears.",
        "whyNecessary": "ALLOW should be grounded in deliberate intent, not just a polite request.",
        "productImpact": "Supports unlock decisions and strictness tuning.",
        "validation": "Must be a finite number between 0 and 100; rounded to an integer.",
        "commonMistakes": "Overrating generic phrases like one quick video without a stop condition."
      },
      {
        "path": "memoryUpdate.behaviorReasonCategory",
        "type": "stress | boredom | loneliness | escape | habit | intentional | other",
        "required": true,
        "example": "boredom",
        "meaning": "The long-term behavior pattern category to remember for the target.",
        "whyNecessary": "Pattern memory needs behavior labels that stay separate from current decision reasoning.",
        "productImpact": "Affects future repeated-pattern context and PM review of remembered behavior.",
        "validation": "Unknown labels are normalized where possible and otherwise become other.",
        "commonMistakes": "Using decision reason labels such as insufficient_reason here."
      },
      {
        "path": "memoryUpdate.patternNote",
        "type": "string | null",
        "required": true,
        "nullable": true,
        "example": "User tends to request vague short video breaks without a clear stop condition.",
        "meaning": "Optional short note about the repeated behavior pattern.",
        "whyNecessary": "The model can preserve useful behavioral context without storing unnecessary transcript detail.",
        "productImpact": "Improves future AI Check context while keeping local memory concise.",
        "validation": "Empty strings become null.",
        "commonMistakes": "Including sensitive or overly detailed personal content when a short pattern note is enough."
      }
    ],
    "example": {
      "decision": "ASK_MORE",
      "userFacingMessage": "What specific task do you need YouTube for, and when will you stop?",
      "decisionReasonCategory": "insufficient_reason",
      "unlockMinutes": null,
      "aiCooldownSeconds": null,
      "scores": {
        "repeatedReason": 20,
        "impulse": 62,
        "deliberateness": 35
      },
      "memoryUpdate": {
        "behaviorReasonCategory": "boredom",
        "patternNote": "User tends to request vague short video breaks without a clear stop condition."
      }
    },
    "schemaSummary": "{ decision, userFacingMessage, decisionReasonCategory, unlockMinutes, aiCooldownSeconds, scores: { repeatedReason, impulse, deliberateness }, memoryUpdate: { behaviorReasonCategory, patternNote } }",
    "promptSchema": {
      "decision": "ALLOW|AI_COOLDOWN|ASK_MORE|BLOCK",
      "userFacingMessage": "string",
      "decisionReasonCategory": "repeated_excuse|clear_intention|high_risk_pattern|low_risk|insufficient_reason",
      "unlockMinutes": "number|null",
      "aiCooldownSeconds": "number|null",
      "scores": {
        "repeatedReason": "number",
        "impulse": "number",
        "deliberateness": "number"
      },
      "memoryUpdate": {
        "behaviorReasonCategory": "stress|boredom|loneliness|escape|habit|intentional|other",
        "patternNote": "string|null"
      }
    }
  },
  "evaluation": {
    "title": "Evaluation Case",
    "summary": "The unified case fixture used to run model regression checks.",
    "fields": [
      {
        "path": "id",
        "type": "string",
        "required": true,
        "example": "under_ask_youtube_strict_001",
        "meaning": "Stable identifier for the evaluation case.",
        "whyNecessary": "Eval results, PM Review edits, and regression history need a durable case id.",
        "productImpact": "Keeps repeated runs and PM edits tied to the same case.",
        "validation": "Must be a non-empty unique string within the case set.",
        "commonMistakes": "Changing ids when only expectations or notes change."
      },
      {
        "path": "title",
        "type": "string",
        "required": true,
        "example": "Vague YouTube break should ask for a boundary",
        "meaning": "Human-readable case name shown in PM Review.",
        "whyNecessary": "PMs need to scan and select cases without reading the full fixture.",
        "productImpact": "Improves review queue and regression suite navigation.",
        "validation": "Must be non-empty.",
        "commonMistakes": "Using a title that only describes the domain but not the expected behavior."
      },
      {
        "path": "versions.promptVersion",
        "type": "string",
        "required": true,
        "example": "ai-check-prompt-v4",
        "meaning": "Prompt Program version this case targets. The stored key is promptVersion for compatibility, but the product meaning is the full Prompt Program: system prompt, decision policy, scoring rubric, prompt-facing schema, parser contract, and fallback behavior.",
        "whyNecessary": "Eval runs need to know whether a case belongs to the current Prompt Program contract or an explicitly older run.",
        "productImpact": "Prevents silently judging old Prompt Program expectations against new prompt policy, rubric, or schema behavior.",
        "validation": "Default eval runs require the current Prompt Program version unless legacy mode is explicit.",
        "commonMistakes": "Treating promptVersion as only the static system prompt string, or omitting versions and making the case look current by accident."
      },
      {
        "path": "versions.outputSchemaVersion",
        "type": "string",
        "required": true,
        "example": "checkpoint-decision-v3",
        "meaning": "Model output schema version this case targets.",
        "whyNecessary": "Expected output fields must align with the model output parser shape.",
        "productImpact": "Prevents eval failures caused by output schema drift rather than model behavior.",
        "validation": "Default eval runs require the current output schema version unless legacy mode is explicit.",
        "commonMistakes": "Updating expectedOutput fields without bumping or checking the output schema version."
      },
      {
        "path": "versions.evaluationSchemaVersion",
        "type": "string",
        "required": true,
        "example": "ai-check-evaluation-v4",
        "meaning": "Evaluation schema version used to interpret eval expectations.",
        "whyNecessary": "EvaluationRunner semantics are versioned separately from model output parsing.",
        "productImpact": "Keeps PM-authored expectations comparable across prompt and model changes.",
        "validation": "Default eval runs require the current evaluation schema version unless legacy mode is explicit.",
        "commonMistakes": "Changing eval expectation semantics without moving the evaluation schema version."
      },
      {
        "path": "input",
        "type": "object",
        "required": true,
        "example": {
          "targetDisplay": "youtube.com",
          "strictness": "strict",
          "sessionContext": {
            "assistantTurnCount": 1,
            "maxAssistantTurns": 5,
            "isFinalTurn": false
          },
          "messages": [
            {
              "role": "user",
              "content": "I just want one quick video.",
              "source": "user"
            }
          ],
          "patternMemorySnapshot": []
        },
        "meaning": "The model input context used for this case.",
        "whyNecessary": "Evaluation must replay a concrete checkpoint context.",
        "productImpact": "Determines what the model sees during the eval.",
        "validation": "Must match the input contract.",
        "commonMistakes": "Writing assertions without preserving the original target, strictness, or messages."
      },
      {
        "path": "input",
        "type": "object",
        "required": true,
        "example": {
          "targetDisplay": "youtube.com",
          "strictness": "strict",
          "sessionContext": {
            "assistantTurnCount": 1,
            "maxAssistantTurns": 5,
            "isFinalTurn": false
          },
          "messages": [
            {
              "role": "user",
              "content": "I just want one quick video.",
              "source": "user"
            }
          ],
          "patternMemorySnapshot": []
        },
        "meaning": "The model input context used for this case.",
        "whyNecessary": "Evaluation must replay a concrete checkpoint context.",
        "productImpact": "Determines what the model sees during the eval.",
        "validation": "Must match the input contract.",
        "commonMistakes": "Writing assertions without preserving the original target, strictness, or messages."
      },
      {
        "path": "output.parsed",
        "type": "object",
        "required": true,
        "meaning": "Optional captured provider output for inspection.",
        "whyNecessary": "Stored outputs help compare provider behavior across runs.",
        "productImpact": "Improves PM review traceability.",
        "validation": "When present, should match the output contract.",
        "commonMistakes": "Treating captured output as the expected assertion."
      },
      {
        "path": "output.parsed",
        "type": "object",
        "required": true,
        "meaning": "Optional captured provider output for inspection.",
        "whyNecessary": "Stored outputs help compare provider behavior across runs.",
        "productImpact": "Improves PM review traceability.",
        "validation": "When present, should match the output contract.",
        "commonMistakes": "Treating captured output as the expected assertion."
      },
      {
        "path": "eval.expectedOutput.decision",
        "type": "ALLOW | AI_COOLDOWN | ASK_MORE | BLOCK | object",
        "required": false,
        "example": "ASK_MORE",
        "meaning": "The expected decision constraint for this case.",
        "whyNecessary": "Every eval case needs one primary pass/fail decision expectation.",
        "productImpact": "Determines the core regression result.",
        "validation": "String values require exact match. Object values may set exact, allowed, and disallowed decision constraints.",
        "commonMistakes": "Using tags as a substitute for expected decision."
      },
      {
        "path": "eval.expectedOutput.userFacingMessage.mustMention",
        "type": "string[]",
        "required": false,
        "example": [
          "time limit",
          "exit plan"
        ],
        "meaning": "Phrases or topics that must appear in the user-facing message.",
        "whyNecessary": "Some ASK_MORE cases need specific missing information.",
        "productImpact": "Catches vague follow-up questions.",
        "validation": "Each phrase is matched case-insensitively against userFacingMessage.",
        "commonMistakes": "Making this too specific to one exact wording."
      },
      {
        "path": "eval.expectedOutput.userFacingMessage.mustNotMention",
        "type": "string[]",
        "required": false,
        "example": [
          "You are weak"
        ],
        "meaning": "Phrases that must not appear in the user-facing message.",
        "whyNecessary": "Tone and safety regressions need explicit negative assertions.",
        "productImpact": "Prevents shame, moral judgment, or unsafe wording.",
        "validation": "Each phrase is matched case-insensitively against userFacingMessage.",
        "commonMistakes": "Using broad words that would fail harmless messages."
      },
      {
        "path": "eval.expectedOutput.decisionReasonCategory",
        "type": "repeated_excuse | clear_intention | high_risk_pattern | low_risk | insufficient_reason",
        "required": false,
        "meaning": "Expected current-decision reason category.",
        "whyNecessary": "Reason expectations catch cases where the decision is right but the model's explanation category is wrong.",
        "productImpact": "Improves diagnosis of strictness and false-positive behavior.",
        "validation": "When present, must exactly match decisionReasonCategory.",
        "commonMistakes": "Using behavior-memory labels here instead of decision reason labels."
      },
      {
        "path": "eval.expectedOutput.aiCooldownSeconds",
        "type": "{ exact?: number|null, min?: number, max?: number }",
        "required": false,
        "meaning": "Expected AI cooldown duration constraint.",
        "whyNecessary": "Cooldown decisions need duration expectations, not just decision labels.",
        "productImpact": "Catches cooldown durations that are too weak or too harsh for the case.",
        "validation": "Exact takes precedence when present; otherwise min and max bound the numeric value.",
        "commonMistakes": "Expecting cooldown seconds for non-cooldown decisions."
      },
      {
        "path": "eval.expectedOutput.scores",
        "type": "object",
        "required": false,
        "example": {
          "impulse": {
            "min": 50,
            "max": 90
          }
        },
        "meaning": "Expected score ranges by output score name.",
        "whyNecessary": "Some cases need the model to get risk strength roughly right even if the decision passes.",
        "productImpact": "Catches weak scoring that can hide borderline behavior.",
        "validation": "Each configured score range checks min and max only for that score.",
        "commonMistakes": "Setting ranges for every score when only one score is important."
      },
      {
        "path": "eval.expectedOutput.scores",
        "type": "object",
        "required": false,
        "example": {
          "impulse": {
            "min": 50,
            "max": 90
          }
        },
        "meaning": "Expected score ranges by output score name.",
        "whyNecessary": "Some cases need the model to get risk strength roughly right even if the decision passes.",
        "productImpact": "Catches weak scoring that can hide borderline behavior.",
        "validation": "Each configured score range checks min and max only for that score.",
        "commonMistakes": "Setting ranges for every score when only one score is important."
      },
      {
        "path": "eval.expectedOutput.memoryUpdate.behaviorReasonCategory",
        "type": "stress | boredom | loneliness | escape | habit | intentional | other",
        "required": false,
        "example": "boredom",
        "meaning": "Expected long-term behavior memory category.",
        "whyNecessary": "Memory expectations catch cases where future pattern context would learn the wrong behavior label.",
        "productImpact": "Protects repeated-pattern learning quality.",
        "validation": "When present, must exactly match memoryUpdate.behaviorReasonCategory.",
        "commonMistakes": "Forgetting memoryUpdate expectations when the bad case is about learned behavior."
      },
      {
        "path": "eval.expectedOutput.memoryUpdate.patternNote",
        "type": "{ exact?: string|null, mustMention?: string[], mustNotMention?: string[] }",
        "required": false,
        "meaning": "Expected memory note constraints.",
        "whyNecessary": "Pattern notes should preserve useful behavior context without over-storing personal detail.",
        "productImpact": "Improves future AI Check context quality.",
        "validation": "Exact checks exact string or null; phrase checks are case-insensitive.",
        "commonMistakes": "Requiring exact prose when topic coverage is enough."
      },
      {
        "path": "eval.expectedInputEvidence.hasExplicitDuration",
        "type": "boolean",
        "required": false,
        "example": false,
        "meaning": "Whether the user's visible messages include a concrete duration or time box.",
        "whyNecessary": "Many prompt failures hinge on whether the user gave a bounded time plan before the model decided.",
        "productImpact": "Lets PMs test evidence quality separately from the final decision label.",
        "validation": "When present, the eval runner derives this boolean from the case input messages before checking model output.",
        "commonMistakes": "Encoding duration evidence only in reviewerNote instead of a machine-checked expectation."
      },
      {
        "path": "eval.expectedInputEvidence.hasReturnPlan",
        "type": "boolean",
        "required": false,
        "example": false,
        "meaning": "Whether the user's visible messages include an explicit plan to return to the original task or stop.",
        "whyNecessary": "Return-task evidence distinguishes deliberate breaks from open-ended browsing.",
        "productImpact": "Improves tests around bounded breaks, school/work tasks, and over-allow regressions.",
        "validation": "When present, the eval runner derives this boolean from the case input messages before checking model output.",
        "commonMistakes": "Treating a duration alone as a return plan when the user did not say what they will return to."
      },
      {
        "path": "eval.tags",
        "type": "string[]",
        "required": true,
        "example": [
          "under_ask",
          "video",
          "strictness"
        ],
        "meaning": "Risk and category labels for filtering eval results.",
        "whyNecessary": "PM Review and eval reporting need grouped risk views.",
        "productImpact": "Drives case sets and tag-level pass rates.",
        "validation": "Must be an array; recommended tags are shared in PM Review.",
        "commonMistakes": "Using tags to encode expected behavior instead of assertions."
      },
      {
        "path": "eval.reviewerNote",
        "type": "string",
        "required": false,
        "example": "Model should ask for a bounded purpose before allowing.",
        "meaning": "PM-authored note explaining the expectation.",
        "whyNecessary": "Reviewer notes preserve the product reasoning behind a case.",
        "productImpact": "Improves future prompt/schema review and case cleanup.",
        "validation": "Optional free text.",
        "commonMistakes": "Putting machine-checked expectations only in reviewerNote instead of expectedOutput."
      },
      {
        "path": "status",
        "type": "draft | ready | archived",
        "required": true,
        "example": "ready",
        "meaning": "PM Review lifecycle status for the case.",
        "whyNecessary": "PM queues need to know whether a case is still being edited, ready to run, or archived.",
        "productImpact": "Controls active, draft, and archive views without encoding dataset purpose.",
        "validation": "Must be draft, ready, or archived.",
        "commonMistakes": "Using status to represent regression or holdout membership instead of datasetType."
      },
      {
        "path": "archivedAt",
        "type": "string",
        "required": false,
        "meaning": "Archive timestamp when the case has been retired.",
        "whyNecessary": "Archived cases should remain traceable without running by default.",
        "productImpact": "Preserves review history while keeping normal eval runs clean.",
        "validation": "Present only when status is archived.",
        "commonMistakes": "Leaving archivedAt on a regression case."
      },
      {
        "path": "archivedReason",
        "type": "string",
        "required": false,
        "meaning": "Optional explanation for archiving the case.",
        "whyNecessary": "PMs need to know why a case was retired.",
        "productImpact": "Reduces duplicate case re-creation and preserves decision context.",
        "validation": "Optional free text.",
        "commonMistakes": "Archiving without explaining what replaced or invalidated the case."
      },
      {
        "path": "datasetType",
        "type": "design | regression | holdout",
        "required": true,
        "example": "regression",
        "meaning": "How this case is used in prompt-engineering experiments.",
        "whyNecessary": "Evaluation needs to separate design coverage, release-gating regressions, and holdout checks from lifecycle status.",
        "productImpact": "Drives Case Library grouping, experiment filters, and release-gate selection.",
        "validation": "Must be design, regression, or holdout.",
        "commonMistakes": "Using lifecycle status such as ready or archived to mean release-gating purpose."
      },
      {
        "path": "provenance.type",
        "type": "authored | session | review",
        "required": true,
        "example": "authored",
        "meaning": "The origin category for this evaluation case.",
        "whyNecessary": "PM Review needs to distinguish authored cases, direct session-derived cases, and PM-reviewed cases without treating review workflow as lifecycle state.",
        "productImpact": "Keeps evidence and creation path clear in Case Library and experiments.",
        "validation": "Must be authored, session, or review.",
        "commonMistakes": "Using provenance as a readiness or dataset label."
      },
      {
        "path": "provenance.author",
        "type": "string",
        "required": false,
        "meaning": "Optional author label for a hand-authored case.",
        "whyNecessary": "Authored design and regression cases may need PM or developer attribution.",
        "productImpact": "Improves accountability during case cleanup.",
        "validation": "Optional string used only when provenance.type is authored.",
        "commonMistakes": "Using author to encode tags or ownership workflow."
      },
      {
        "path": "provenance.sessionId",
        "type": "string",
        "required": false,
        "meaning": "Original AI Check session id when the case came from a real session or review.",
        "whyNecessary": "Real-session cases must remain traceable to source behavior.",
        "productImpact": "Allows Review and Case Library to link back to the observed decision context.",
        "validation": "Required for session and review provenance.",
        "commonMistakes": "Dropping session id when converting a bad case to eval."
      },
      {
        "path": "provenance.decisionId",
        "type": "string",
        "required": false,
        "meaning": "Original decision id for the selected decision point.",
        "whyNecessary": "Turn-level evals need to identify the exact model decision that was reviewed.",
        "productImpact": "Prevents whole-session confusion when a middle turn was wrong.",
        "validation": "Required for session and review provenance.",
        "commonMistakes": "Pointing to the final decision when the reviewed failure happened earlier."
      },
      {
        "path": "provenance.reviewId",
        "type": "string",
        "required": false,
        "meaning": "PM review record id when the case was created from a BadCaseReview.",
        "whyNecessary": "The eval case should trace back to the reviewer judgment without making review a source enum.",
        "productImpact": "Preserves review rationale and audit trail.",
        "validation": "Required when provenance.type is review.",
        "commonMistakes": "Using bad_case_review as a source value instead of a review provenance reference."
      },
      {
        "path": "lineage.parentCaseId",
        "type": "string",
        "required": false,
        "meaning": "Optional parent case id when this case was derived from another case.",
        "whyNecessary": "Case cleanup may split or refine prior cases while preserving ancestry.",
        "productImpact": "Helps PMs understand why similar cases exist.",
        "validation": "Optional string.",
        "commonMistakes": "Using lineage to duplicate session or review provenance."
      },
      {
        "path": "lineage.supersedesCaseIds",
        "type": "string[]",
        "required": false,
        "meaning": "Optional case ids that this case replaces.",
        "whyNecessary": "Broader or cleaner cases can retire older cases without losing traceability.",
        "productImpact": "Supports archive decisions and duplicate cleanup.",
        "validation": "Optional array of case ids.",
        "commonMistakes": "Hard-deleting replaced cases instead of archiving them."
      },
      {
        "path": "lineage.splitFromCaseId",
        "type": "string",
        "required": false,
        "meaning": "Optional source case id when this case was split out from a broader case.",
        "whyNecessary": "PMs may split overloaded cases into focused decision-point tests.",
        "productImpact": "Keeps case refactors understandable.",
        "validation": "Optional string.",
        "commonMistakes": "Using one broad case for unrelated failure modes."
      },
      {
        "path": "lineage.mergedFromCaseIds",
        "type": "string[]",
        "required": false,
        "meaning": "Optional case ids merged into this case.",
        "whyNecessary": "Duplicate case cleanup should preserve ancestry.",
        "productImpact": "Reduces suite noise while keeping traceability.",
        "validation": "Optional array of case ids.",
        "commonMistakes": "Archiving duplicates without recording the replacement."
      }
    ],
    "example": {
      "id": "under_ask_youtube_strict_001",
      "title": "Vague YouTube break should ask for a boundary",
      "versions": {
        "promptVersion": "ai-check-prompt-v4",
        "outputSchemaVersion": "checkpoint-decision-v3",
        "evaluationSchemaVersion": "ai-check-evaluation-v4"
      },
      "input": {
        "targetDisplay": "youtube.com",
        "strictness": "strict",
        "sessionContext": {
          "assistantTurnCount": 1,
          "maxAssistantTurns": 5,
          "isFinalTurn": false
        },
        "messages": [
          {
            "role": "user",
            "content": "I just want one quick video.",
            "source": "user"
          }
        ],
        "patternMemorySnapshot": []
      },
      "eval": {
        "expectedOutput": {
          "decision": "ASK_MORE",
          "userFacingMessage": {
            "mustMention": [
              "time limit",
              "exit plan"
            ],
            "mustNotMention": [
              "You are weak"
            ]
          },
          "scores": {
            "impulse": {
              "min": 50,
              "max": 90
            }
          },
          "memoryUpdate": {
            "behaviorReasonCategory": "boredom"
          }
        },
        "expectedInputEvidence": {
          "hasExplicitDuration": false,
          "hasReturnPlan": false
        },
        "tags": [
          "under_ask",
          "video",
          "strictness"
        ],
        "reviewerNote": "Model should ask for a bounded purpose before allowing."
      },
      "status": "ready",
      "datasetType": "regression",
      "provenance": {
        "type": "authored"
      }
    }
  }
} as const;

export const AI_CHECK_CONTRACT = {
  ...rawContract,
  sections: GENERATED_SECTIONS
} as unknown as AICheckContract;
export const AI_CHECK_CURRENT_VERSIONS = AI_CHECK_CONTRACT.current;

export const AI_CHECK_BAD_CASE_ERROR_TYPES = AI_CHECK_CONTRACT.pmReview.errorTypes;
export const AI_CHECK_COMMON_TAGS = AI_CHECK_CONTRACT.pmReview.commonTags;
export const AI_CHECK_CASE_SETS = AI_CHECK_CONTRACT.pmReview.caseSets;
export const AI_CHECK_SESSION_POLICY = AI_CHECK_CONTRACT.sessionPolicy;
export const AI_CHECK_PROMPT_PROGRAM = AI_CHECK_CONTRACT.promptProgram;
export const AI_CHECK_DECISION_POLICY_RULES = AI_CHECK_PROMPT_PROGRAM.decisionPolicyRules;
export const AI_CHECK_SCORING_RULES = AI_CHECK_PROMPT_PROGRAM.scoringRules;

export const AI_CHECK_INPUT_FIELD_REFERENCE = AI_CHECK_CONTRACT.sections.input.fields;
export const AI_CHECK_OUTPUT_FIELD_REFERENCE = AI_CHECK_CONTRACT.sections.output.fields;
export const AI_CHECK_EVALUATION_FIELD_REFERENCE = AI_CHECK_CONTRACT.sections.evaluation.fields;

export const AI_CHECK_INPUT_EXAMPLE = AI_CHECK_CONTRACT.sections.input.example;
export const AI_CHECK_OUTPUT_EXAMPLE = AI_CHECK_CONTRACT.sections.output.example;
export const AI_CHECK_EVALUATION_EXAMPLE = AI_CHECK_CONTRACT.sections.evaluation.example;

export const AI_CHECK_OUTPUT_SCHEMA_SUMMARY = AI_CHECK_CONTRACT.sections.output.schemaSummary;
export const AI_CHECK_OUTPUT_PROMPT_SCHEMA = AI_CHECK_CONTRACT.sections.output.promptSchema;

export interface AICheckShapeValidationOptions {
  label?: string;
  enumMode?: "strict" | "provider";
}

export function validateAIContractOutputShape(
  value: unknown,
  options: AICheckShapeValidationOptions = {}
): string[] {
  return validateSchemaValue(AI_CHECK_CONTRACT.schemas.output, value, options.label ?? "output", options);
}

export function assertAIContractOutputShape(value: unknown, options: AICheckShapeValidationOptions = {}): void {
  const errors = validateAIContractOutputShape(value, options);
  if (errors.length > 0) {
    throw new Error(errors.join(" "));
  }
}

export function validateAICheckCaseShape(value: unknown, options: AICheckShapeValidationOptions = {}): string[] {
  return validateSchemaValue(AI_CHECK_CONTRACT.schemas.evaluation, value, options.label ?? "case", options);
}

export function assertAICheckCaseShape(value: unknown, options: AICheckShapeValidationOptions = {}): void {
  const errors = validateAICheckCaseShape(value, options);
  if (errors.length > 0) {
    throw new Error(errors.join(" "));
  }
}

function validateSchemaValue(
  rawNode: AICheckContractSchemaNode,
  value: unknown,
  label: string,
  options: AICheckShapeValidationOptions
): string[] {
  const errors: string[] = [];
  validateNode(rawNode, value, label, options, errors);
  return errors;
}

function validateNode(
  rawNode: AICheckContractSchemaNode,
  value: unknown,
  label: string,
  options: AICheckShapeValidationOptions,
  errors: string[]
): void {
  if (value === undefined) {
    if (rawNode.required) errors.push(`${label} is required.`);
    return;
  }
  if (value === null) {
    if (!("nullable" in rawNode && rawNode.nullable)) errors.push(`${label} must not be null.`);
    return;
  }

  const node = resolveSchemaNode(rawNode);
  switch (node.type) {
    case "string":
      if (typeof value !== "string" || (node.required && value.length === 0)) errors.push(`${label} must be a non-empty string.`);
      return;
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value)) {
        errors.push(`${label} must be a finite number.`);
        return;
      }
      if (typeof node.min === "number" && value < node.min) errors.push(`${label} must be >= ${node.min}.`);
      if (typeof node.max === "number" && value > node.max) errors.push(`${label} must be <= ${node.max}.`);
      return;
    case "boolean":
      if (typeof value !== "boolean") errors.push(`${label} must be a boolean.`);
      return;
    case "enum": {
      if (typeof value !== "string") {
        errors.push(`${label} must be a string enum value.`);
        return;
      }
      const providerLoose =
        options.enumMode === "provider" &&
        (label.endsWith("decisionReasonCategory") || label.endsWith("behaviorReasonCategory"));
      if (!providerLoose && !enumValues(node).includes(value)) errors.push(`${label} has invalid enum value ${value}.`);
      return;
    }
    case "array":
      if (!Array.isArray(value)) {
        errors.push(`${label} must be an array.`);
        return;
      }
      value.forEach((item, index) => validateNode(node.item, item, `${label}[${index}]`, options, errors));
      return;
    case "object":
      if (!isRecord(value)) {
        errors.push(`${label} must be an object.`);
        return;
      }
      for (const [key, child] of Object.entries(node.fields)) {
        validateNode(child, value[key], `${label}.${key}`, options, errors);
      }
      return;
    case "union": {
      const variantErrors = node.variants.map((variant) => validateSchemaValue(variant, value, label, options));
      if (!variantErrors.some((items) => items.length === 0)) errors.push(`${label} did not match any allowed shape.`);
      return;
    }
    case "nullableNumberExpectation":
      validateNullableNumberExpectation(value, label, errors);
      return;
    case "nullableTextExpectation":
      validateNullableTextExpectation(value, label, errors);
      return;
    case "numberRangeExpectation":
      validateNumberRangeExpectation(value, label, errors);
      return;
    default:
      errors.push(`${label} has unsupported schema node type ${(node as { type: string }).type}.`);
  }
}

function resolveSchemaNode(node: AICheckContractSchemaNode): AICheckContractSchemaNode {
  if (node.type !== "ref") return node;
  return {
    ...AI_CHECK_CONTRACT.schemas[node.ref],
    required: node.required
  };
}

function enumValues(node: Extract<AICheckContractSchemaNode, { type: "enum" }>): string[] {
  if (node.values) return node.values;
  return node.enum ? ((AI_CHECK_CONTRACT.enums as Record<string, string[]>)[node.enum] ?? []) : [];
}

function validateNullableNumberExpectation(value: unknown, label: string, errors: string[]): void {
  if (!isRecord(value)) {
    errors.push(`${label} must be an object.`);
    return;
  }
  if ("exact" in value && typeof value.exact !== "number" && value.exact !== null) errors.push(`${label}.exact must be number or null.`);
  if ("min" in value && typeof value.min !== "number") errors.push(`${label}.min must be a number.`);
  if ("max" in value && typeof value.max !== "number") errors.push(`${label}.max must be a number.`);
}

function validateNullableTextExpectation(value: unknown, label: string, errors: string[]): void {
  if (!isRecord(value)) {
    errors.push(`${label} must be an object.`);
    return;
  }
  if ("exact" in value && typeof value.exact !== "string" && value.exact !== null) errors.push(`${label}.exact must be string or null.`);
  validateStringArray(value.mustMention, `${label}.mustMention`, errors);
  validateStringArray(value.mustNotMention, `${label}.mustNotMention`, errors);
}

function validateNumberRangeExpectation(value: unknown, label: string, errors: string[]): void {
  if (!isRecord(value)) {
    errors.push(`${label} must be an object.`);
    return;
  }
  if ("min" in value && typeof value.min !== "number") errors.push(`${label}.min must be a number.`);
  if ("max" in value && typeof value.max !== "number") errors.push(`${label}.max must be a number.`);
}

function validateStringArray(value: unknown, label: string, errors: string[]): void {
  if (value === undefined) return;
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) errors.push(`${label} must be a string array.`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}

function resolveSchemaRegistry(
  entries: AICheckVersionRegistryEntry[],
  currentVersion: string,
  currentSection: AICheckContractSection
): AICheckResolvedVersionEntry[] {
  const resolved = entries.map((entry) => ({
    version: entry.version,
    label: entry.label,
    current: entry.current ?? entry.version === currentVersion,
    section: entry.section ?? currentSection
  }));

  if (resolved.some((entry) => entry.version === currentVersion)) {
    return resolved;
  }

  return [
    {
      version: currentVersion,
      label: currentVersion,
      current: true,
      section: currentSection
    },
    ...resolved
  ];
}

export const AI_CHECK_PROMPT_VERSIONS = AI_CHECK_CONTRACT.versionRegistry.prompts.map((entry) => ({
  version: entry.version,
  label: entry.label,
  current: entry.current ?? entry.version === AI_CHECK_CURRENT_VERSIONS.promptVersion
}));

export const AI_CHECK_OUTPUT_SCHEMA_VERSIONS = resolveSchemaRegistry(
  AI_CHECK_CONTRACT.versionRegistry.outputSchemas,
  AI_CHECK_CURRENT_VERSIONS.outputSchemaVersion,
  AI_CHECK_CONTRACT.sections.output
);

export const AI_CHECK_EVALUATION_SCHEMA_VERSIONS = resolveSchemaRegistry(
  AI_CHECK_CONTRACT.versionRegistry.evaluationSchemas,
  AI_CHECK_CURRENT_VERSIONS.evaluationSchemaVersion,
  AI_CHECK_CONTRACT.sections.evaluation
);
